<?php
//INICIAR LA SESIÓN Y CONEXIÓN A BD
require_once 'includes/conexion.php';

//RECOGER DATOS DEL FORMULARIO

//COMPROBAR LA CONTRASEÑA

//CONSULTA PARA COMPROBAR LAS CREDENCIALES DEL USUARIO

//UTILIZAR UNA SESIÓN PARA GUARDAR LOS DATOS DEL USUARIO LOGUEADO

// SI HALGO FALLA ENVIAR UNA SESIÓN CON EL FALLO

//REDIRIGIR AL INDEX.PHP